#!/bin/sh

case "$1" in
  start)
	ifconfig lo 127.0.0.1
	ifconfig eth0 192.168.2.26 netmask 255.255.255.0
	route add default gw 192.168.2.1 dev eth0 metric 0
	echo "nameserver 114.114.114.114 # eth0" > /tmp/resolv.conf
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
